# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-25 05:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recsys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('url_name', models.CharField(max_length=40)),
                ('repo_base', models.CharField(max_length=40)),
                ('repo_name', models.CharField(max_length=140)),
                ('item_table_name', models.CharField(max_length=140)),
                ('primary_key_field', models.CharField(max_length=140)),
                ('title_field', models.CharField(max_length=140)),
                ('description_field', models.CharField(max_length=140)),
                ('image_link_field', models.CharField(max_length=140)),
                ('universal_code_field', models.CharField(max_length=140)),
                ('template', models.TextField()),
                ('status', models.CharField(default=b'paused', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
