# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-18 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recsys',
            name='solr_core_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
