# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-23 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='universal_code',
            field=models.CharField(max_length=999, null=True),
        ),
    ]
